# generated by datamodel-codegen:
#   filename:  http://localhost:3000/api-json
#   timestamp: 2023-11-30T13:16:51+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class AddressDto(BaseModel):
    city: str
    address: str
    description: Optional[str] = None


class ClientDto(BaseModel):
    first_name: str
    last_name: str
    patronymic: Optional[str] = None
    addresses: List[AddressDto]
    phone: str = Field(..., example='+79852668147')
    about_client: Optional[str] = Field(None, example='Пажилой клиент')


class ClientSuccessResDto(BaseModel):
    message: str = Field(..., example='Сообщение об успешной операции!')
    data: ClientDto


class UpdateClientReqDto(BaseModel):
    first_name: Optional[str] = None
    last_name: Optional[str] = None
    patronymic: Optional[str] = None
    addresses: Optional[List[AddressDto]] = None
    phone: Optional[str] = Field(None, example='+79852668147')
    about_client: Optional[str] = Field(None, example='Пажилой клиент')


class SearchClientsReqDto(BaseModel):
    first_name: Optional[str] = None
    addresses: Optional[List[AddressDto]] = None
    phone: Optional[str] = Field(None, example='+79852668147')


class PageMetaDto(BaseModel):
    page: float
    limit: float
    itemCount: float
    pageCount: float
    hasPreviousPage: bool
    hasNextPage: bool


class GetClientsReqDto(BaseModel):
    meta: PageMetaDto
    data: List[ClientDto]
